version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    open-pull-requests-limit: 5
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "gradle"

  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 5
    schedule:
      interval: "daily"